version: '3.1'

services:
    wordpress:
        image: wordpress
        restart: always
        ports:
            - 5555:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: user
            WORDPRESS_DB_PASSWORD: pass
            WORDPRESS_DB_NAME: db
        volumes:
            - ./wordpress:/var/www/html

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_RANDOM_ROOT_PASSWORD: 'root'
        volumes:
            - ./datas:/var/lib/mysql
            - ./DumpSQL/aldiBnB_db.sql:/docker-entrypoint-initdb.d/aldiBnB_db.sql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1

